### ISSUE TITLE
Project URL 404's

### ISSUE THREAD

**Issue by kusold** [yanyaoli/circular_avatar_beautifier#1]
Thanks for creating this. It was perfect for making a round avatar for my Github bot.

It looks like you renamed your GH user, but the project still points to your old username. The new url should be: https://yanyaoli.github.io/circular_avatar_beautifier/

<img width="342" alt="image" src="https://github.com/yanyaoli/circular_avatar_beautifier/assets/509966/167451d1-ea7d-429a-b569-8570b38f5863">

**Comment by yanyaoli** [comment]
Thank you for using this project, the issues have been resolved, feel free to raise any further questions or concerns in the issue. Thanks again for your feedback and support! Best wishes to you!
